apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T13:46:38Z"
  name: carts-canary
  resourceVersion: "952310"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: e59d768f-6467-11ea-a1bc-42010a8401b3
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
