apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T13:51:40Z"
  name: carts-canary
  resourceVersion: "953645"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 9992fe91-6468-11ea-a1bc-42010a8401b3
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
